### ISSUE TITLE
Error in findThreshold mutations

### ISSUE THREAD

**Issue by jamesrpriest** [raphael-group/hotnet2#27]
Getting a complaint about an unreferenced local variable when I run findThreshold mutations with the following input;

findThreshold.py mutations -r MAF0.1.CADD0.mutations.iref -if /home/storage/jpriest_backup/zoran/priest_apps/hotnet2-master/influence_matrices/irefindex/index_genes_uniform -hf ./MAF0.1.CADD0.heat -n 5 -c 16 -o ./MAF0.1.CADD0.iref.deltas.mutation  -mf /home/storage/jpriest_backup/zoran/priest_apps/hotnet2-master/influence_matrices/irefindex/iref_ppr_0.55.mat -glf refflat.glf -gof refflat.gof -b 0.003 --bmr_file corr.bmr.MAF0.1.CADD0.combined.bmr
- Performing permuted mutation data delta selection...
  Traceback (most recent call last):
  File "/home/storage/jpriest_backup/zoran/priest_apps/hotnet2-master/bin/findThreshold.py", line 161, in <module>
    run(get_parser().parse_args(sys.argv[1:]))
  File "/home/storage/jpriest_backup/zoran/priest_apps/hotnet2-master/bin/findThreshold.py", line 102, in run
    deltas = get_deltas_for_mutations(args, infmat, infmat_index, heat_params)
  File "/home/storage/jpriest_backup/zoran/priest_apps/hotnet2-master/bin/findThreshold.py", line 147, in get_deltas_for_mutations
    heat_params["min_freq"], args.num_permutations, args.num_cores)
  File "/home/storage/jpriest_backup/zoran/priest_apps/hotnet2-master/hotnet2/permutations.py", line 117, in generate_mutation_permutation_heat
    genes = set([snv.gene for snv in snvs] + [cna.gene for cna in cnas])
  UnboundLocalError: local variable 'snvs' referenced before assignment

**Comment by matthewreyna** [comment]
This issue should be fixed in the current version of the code.
